# GitHub Pages configuration
title: "IAM Lifecycle Demo Platform"
description: "Complete Identity and Access Management lifecycle platform with FastAPI backend, interactive dashboard, and automated SaaS integration"
url: "https://mdisturbed.github.io"
baseurl: "/iam-lifecycle-demo"

# Theme
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: mdisturbed
lang: en_US

# Navigation
navigation:
  - title: Home
    url: /
  - title: Demo
    url: /#demo
  - title: Documentation
    url: /README
  - title: GitHub
    url: https://github.com/mdisturbed/iam-lifecycle-demo

# Social
github_username: mdisturbed
repository: mdisturbed/iam-lifecycle-demo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Exclude files from processing
exclude:
  - backend/
  - samples/
  - .env.example
  - compose.yaml
  - verify-deployment.sh
  - Gemfile*
  - README.md
  - DEPLOY.md
  - SECURITY.md
