services:
  api:
    build: ./backend
    env_file: .env
    depends_on:
      - db
      - redis
      - worker
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  worker:
    build:
      context: ./backend
      dockerfile: celery.Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: iam
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: iam
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
